### ISSUE TITLE
Improve example

### ISSUE THREAD

**Issue by janhancic** [BladeRunnerJS/browser-modules#7]
Could you add `module2` source to the example in [sub relams](https://github.com/BladeRunnerJS/browser-modules#sub-realms) section? So the reader can get a complete picture.

**Comment by dchambers** [comment]
Hi @janhancic, the test was supposed to be for the `acme/module2` module that I'd previously introduced, but this wasn't previously obvious, so I've updated the documentation.

**Comment by janhancic** [comment]
:+1:
