### ISSUE TITLE
using browser-modeles in node.js

### ISSUE THREAD

**Issue by aogilvie** [BladeRunnerJS/browser-modules#9]
When using this in Node.js shouldn't `realm.install();` in install.js be wrapped with (for example):

```
if (typeof module !== 'undefined') {
    // for node.js
} else {
    // for the browser
        realm.install()
}
```

as done in the bottom of `browser-modules.js`, else `window.realm` will be undefined in Node.js?

**Comment by dchambers** [comment]
Hi @aogilvie, `install.js` shouldn't be loaded in Node.js environments. If you look in `package.json` you see that `main` points only to `browser-modules.js`.

**Comment by dchambers** [comment]
Admittedly, I'm not 100% sure why `realm.install()` is performed in a separate file, but suppose it's because installing this in Node.js would prevent normal `require()` invocations from working. @kybernetikos would know the answer to this question for sure though.

**Comment by aogilvie** [comment]
Thanks. Yeah I didn't install via npm, was playing with brjs build-app to an electron app which seemed to have picked up this line of code. Electron ships with window.modules which triggered the part of the if condition I didn't want (electron being a staticly wrapped file server). I suppose I was just interested in how brjs picks up the code in install.js. I'm not at office so I don't remember exactly how that was being picked up. I'll closer for now and try with npm later.

**Comment by dchambers** [comment]
> I suppose I was just interested in how brjs picks up the code in install.js.

Ah, in that case I can answer the question. It's because `thirdparty-lib.manifest` contains this line:

``` js
js: browser-modules.js, install.js
```
